# Site settings
title: Victor Igor - Desenvolvedor Web
description: "Um blog sobre desenvolvimento web"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://victorvoid.github.io" #http://localhost:3000

# User settings
username: victor igor
user_title: Victor Igor - FrontEnd
email: victor.0w3@hotmail.com
twitter_username: victorvoid_
github_username:  victorvoid
gplus_username:  victor0w3
disqus_username: victorvoid

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: home
    url: /
  - title: meus posts
    url: /posts
  - title: series
    url: /series
  - title: tags
    url: /tags
  - title: sobre mim
    url: /about
# projects in header index
projects:
  - name: fluany
    url: https://github.com/fluany
  - name: vim-frontend
    url: https://github.com/victorvoid/vim-frontend
  - name: generator-capybara
    url: https://github.com/victorvoid/generator-capybara
  - name: space-jekyll-template
    url: https://github.com/victorvoid/space-jekyll-template
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
